name: Mirror to Origin Repo

on:
  push:
    branches:
      - demo

jobs:
  mirror_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Origin Remote
        run: |
          git remote add target-mirror https://oauth2:${{ secrets.TMA_TOKEN }}@gitsdc.tma.com.vn/mcare/t-va.git
          git push --force target-mirror demo:demo